### ISSUE TITLE
The ~ won't work.

### ISSUE THREAD

**Issue by SimpSim** [GSRHackZ/Google-Meet-Spam-Bot#2]
I managed to make the script running in Tampermonkey, but when I go to google meet and click ~, Nothing happens.

**Comment by LeonardoFCorrea** [comment]
Same problem: "I managed to make the script running in Tampermonkey, but when I go to google meet and click ~, Nothing happens."

**Comment by GSRHackZ** [comment]
What device do you have, this may be the issue. I will test it on my other device and see.
