### ISSUE TITLE
uhhh explain like im five

### ISSUE THREAD

**Issue by MaxiGGaming** [GSRHackZ/Google-Meet-Spam-Bot#5]
i dont get how to run it. i downloaded tampermonkey but i dont know what to do. i paste the code and what do i do then. i tried ~ but that doesnt do anything

**Comment by GSRHackZ** [comment]
What device do you have?

**Comment by MaxiGGaming** [comment]
PC

**Comment by GSRHackZ** [comment]
what type pc

**Comment by MaxiGGaming** [comment]
Win 10 desktop

**Comment by GSRHackZ** [comment]
what browser are you using?

**Comment by MaxiGGaming** [comment]
Google

**Comment by GSRHackZ** [comment]
ok I want you to try it again right now. Open console when clicking ~ and see if there are any errors.

**Comment by MaxiGGaming** [comment]
I can’t rn

**Comment by MaxiGGaming** [comment]
I’m not on my pc

**Comment by GSRHackZ** [comment]
ok the next time you can tell me right here. Imma do a whole rewrite of the code and try to fix as many of these bugs as possible. I wrote this code 8 months ago so It's pretty jank 😂

**Comment by MaxiGGaming** [comment]
Do I need to be on a specific tab to do it? How do I change the mail and stuff. I run it and nothing happens

**Comment by MaxiGGaming** [comment]
> ok the next time you can tell me right here. Imma do a whole rewrite of the code and try to fix as many of these bugs as possible. I wrote this code 8 months ago so It's pretty jank 😂

lmao

**Comment by GSRHackZ** [comment]
> Do I need to be on a specific tab to do it? How do I change the mail and stuff. I run it and nothing happens

Nope, it's just this code is rly bad XD, imma start fixing it rn.

**Comment by MaxiGGaming** [comment]
thx dude I don’t even know how to code.

**Comment by GSRHackZ** [comment]
No problem, and you should learn. It's mad fun, especially making userscripts.

**Comment by MaxiGGaming** [comment]
I’ll try, the thing is I don’t know where to start, and what language to learn.

**Comment by GSRHackZ** [comment]
Heres a link: https://www.youtube.com/watch?v=PkZNo7MFNFg

I learned from this when I was a beginner.

**Comment by MaxiGGaming** [comment]
thx!

**Comment by GSRHackZ** [comment]
Changed controls & added more info ⭐

Controls are now Ctrl + Alt + B.

I made it easier to use and added more info in description to make it understandable.
